language: android
jdk:
  - oraclejdk8
dist: trusty
sudo: required
env:
  global:
    - ANDROID_BUILD_TOOLS=28.0.3
    - ADB_INSTALL_TIMEOUT=5
    - ANDROID_API=28
    - CC=clang
    - CXX=clang++
    - CMAKE_C_COMPILER=clang
    - CMAKE_CXX_COMPILER=clang++
android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services
    - addon-google_apis-google-19
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
before_install:
  - sudo chmod +x gradlew
install:
  - echo y | sdkmanager 'ndk;16.1.4479499'
  - echo y | sdkmanager 'cmake;3.6.4111459'
before_script:
  - touch local.properties
  - "./gradlew clean"
script:
  - ./gradlew assembleDebug
before_deploy:
- export TRAVIS_TAG="1.0.$TRAVIS_BUILD_NUMBER"
- echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
- git config --local user.name "$USER_NAME"
- git config --local user.email "$USER_EMAIL"
- git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
deploy:
  - provider: releases
    api_key: $GITHUB_API_TOKEN
    tag_name: $TRAVIS_TAG
    name: $TRAVIS_TAG
    overwrite: true
    file: app/build/outputs/apk/debug/*
    file_glob: true
    skip_cleanup: true
    on:
      branch: master
